title: Welcome
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://carlrobert.github.io

aux_links:
  Template Repository: https://github.com/carlrobert/carlrobert.github.io
