title: Welcome
description: Leap Day is a theme for GitHub Pages
show_downloads: false
google_analytics:
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
toc:
  min_level: 1
  max_level: 2
